name: ti
channels:
  - fvcore
  - iopath
  - bottler
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - menpo
dependencies:
  - python=3.10
  - pip=24.2
  - wheel==0.38.4
  - fvcore=0.1.5.post20221221
  - iopath=0.1.9
  - nvidiacub
  - cudatoolkit=11.8.0
  - pytorch=2.0.0
  - torchvision=0.15.2
  # - pytorch-cuda=11.8
  - pytorch3d=0.7.5
  - numba==0.59.1
  - gym=0.26.1
  - cython=3.0.10
  - tensorboard=2.13.0
  - tensorboardx=2.6.2.2
  - scikit-video=1.1.11
  - eigen=3.4.0
  - glew
  - mesalib
  - glfw3
  - boost-cpp  
  - boost     
  - pip:
    - absl-py==1.4.0
    - ipywidgets==8.1.2
    - numpy==1.26.4
    - scipy==1.12.0
    - scikit-learn==1.4.1.post1
    - scikit-image==0.22.0
    - pyyaml==6.0.1
    - ruamel.yaml==0.18.6
    - ninja==1.11.1.1
    - h5py==3.10.0
    - pybind11==2.12.0
    - imageio==2.34.0
    - imageio-ffmpeg==0.4.9
    - opencv-python==4.9.0.80
    - opencv-python-headless==4.9.0.80
    - opencv-contrib-python==4.9.0.80
    - plotly==5.20.0
    - open3d==0.18.0
    - pysdf==0.1.9
    - trimesh==4.2.2
    - xatlas==0.0.9
    - pyrender==0.1.45
    - pyOpenGL==3.1.0
    - pyOpenGL_accelerate==3.1.7
    - meshcat==0.3.2
    - webdataset==0.2.86
    - omegaconf==2.3.0
    - pypng==0.20220715.0
    - Panda3D==1.10.14
    - simplejson==3.19.2
    - bokeh==3.4.0
    - roma==1.4.4
    - seaborn==0.13.2
    - pin==2.7.0
    - openpyxl==3.1.2
    - torchnet==0.0.4
    - torchgeometry==0.1.2
    - wandb==0.16.5
    - colorama==0.4.6
    - GPUtil==1.4.0
    - imgaug==0.4.0
    - xlsxwriter==3.2.0
    - albumentations==1.4.2
    - nodejs==0.1.1
    - jupyterlab==4.1.5
    - objaverse==0.1.7
    - g4f==0.2.7.1
    - ultralytics==8.0.120
    - pycocotools==2.0.7
    - py-spy==0.3.14
    - pybullet==3.2.6
    - videoio==0.2.8
    - kornia==0.7.2
    - einops==0.7.0
    - transformations==2024.6.1
    - joblib==1.3.2
    - warp-lang==1.0.2
    - cupy-cuda11x==12.2.0
    - easydict==1.13
    - json_tricks==3.17.3
    - atomics==1.0.2
    - addict==2.4.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - aliyun-python-sdk-core==2.15.1
    - aliyun-python-sdk-kms==2.16.3
    - antlr4-python3-runtime==4.9.3
    - anyio==4.4.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - array_record==0.5.1
    - arrow==1.3.0
    - asciitree==0.3.3
    - asttokens==2.2.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - Babel==2.15.0
    - backcall==0.2.0
    - bddl==1.0.1
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - boto3==1.34.148
    - botocore==1.34.148
    - cachetools==5.4.0
    - chumpy==0.70
    - click==8.1.3
    - cloudpickle==1.6.0
    - cmake==3.27.2
    - comm==0.2.2
    - ConfigArgParse==1.5.3
    - contourpy==1.2.1
    - crcmod==1.7
    - cryptography==43.0.0
    - cycler==0.12.1
    - dash==2.7.1
    - dask==2024.7.1
    - dask-ml==2024.4.4
    - tornado==6.4.1
    - debugpy==1.8.2
    - decorator==4.4.2
    - deepspeed==0.11.1
    - defusedxml==0.7.1
    - diffusers==0.20.1
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - egl-probe==1.0.2
    - entrypoints==0.4
    - environs==9.5.0
    - etils==1.5.2
    - evdev==1.7.1
    - exceptiongroup==1.2.2
    - executing==1.2.0
    - fairscale==0.4.4
    - Farama-Notifications==0.0.4
    - fasteners==0.19
    - fastjsonschema==2.20.0
    - filelock==3.14.0
    - filterpy==1.4.5
    - flatbuffers==24.3.25
    - flow-vis==0.1
    - fonttools==4.53.1
    - fqdn==1.5.1
    - freetype-py==2.4.0
    - frozenlist==1.4.1
    - ftfy==6.2.0
    - future==0.18.2
    - gast==0.4.0
    - gdown==5.2.0
    - gitdb==4.0.11
    - GitPython==3.1.43
    - glfw==2.6.2
    - google-auth==2.32.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - googleapis-common-protos==1.63.2
    - grpcio==1.65.1
    - hjson==3.1.0
    - hpack==4.0.0
    - huggingface-hub==0.24.2
    - hydra-core==1.3.2
    - importlib_metadata==8.2.0
    - importlib_resources==6.4.0
    - iniconfig==2.0.0
    - ipdb==0.13.13
    - ipykernel==6.27.1
    - ipython==8.12.2
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - Jinja2==3.1.2
    - jmespath==0.10.0
    - json-tricks==3.17.3
    - json5==0.9.14
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - keras==2.13.1
    - kiwisolver==1.4.5
    - lazy_loader==0.4
    - libclang==18.1.1
    - lightning==2.1.0
    - lightning-utilities==0.9.0
    - line-profiler==4.1.1
    - lit==16.0.6
    - llvmlite==0.42.0
    - locket==1.0.0
    - Markdown==3.6
    - markdown-it-py==3.0.0
    - MarkupSafe==2.1.1
    - marshmallow==3.21.3
    - matplotlib==3.8.3
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.4.1
    - mdurl==0.1.2
    - mediapy==1.2.0
    - mistune==3.0.2
    - mmpose==0.28.0
    - model-index==0.1.11
    - moviepy==1.0.3
    - mujoco==2.3.7
    - multidict==6.0.5
    - munkres==1.1.4
    - natsort==8.4.0
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.5.6
    - notebook==7.0.6
    - notebook_shim==0.2.3
    - numcodecs==0.12.1
    - oauthlib==3.2.2
    - opendatalab==0.0.10
    - openmim==0.3.9
    - opt-einsum==3.3.0
    - ordered-set==4.1.0
    - oss2==2.17.0
    - overrides==7.7.0
    - packaging==24.1
    - pandas==2.0.3
    - pandocfilters==1.5.1
    - parso==0.8.3
    - partd==1.4.2
    - pathtools==0.1.2
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - platformdirs==4.2.2
    - pluggy==1.5.0
    - plyfile==1.0.3
    - proglog==0.1.10
    - prometheus_client==0.20.0
    - promise==2.3
    - prompt-toolkit==3.0.36
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - py-cpuinfo==9.0.0
    - pyasn1==0.6.0
    - pyasn1_modules==0.4.0
    - pybullet-svl==3.1.6.4
    - pycocoevalcap==1.2
    - pycryptodome==3.20.0
    # - pydantic==1.10.17
    - Pygments==2.13.0
    - pynput==1.7.6
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrsistent==0.19.2
    - pytest==8.3.2
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - python-xlib==0.33
    - pytorch-lightning==2.1.0
    - pytz==2023.4
    - pyzmq==24.0.1
    - referencing==0.35.1
    - regex==2024.7.24
    - requests>=2.28.0,<3.0
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.4.2
    - rpds-py==0.19.1
    - rsa==4.9
    - s3transfer==0.10.2
    - safetensors==0.4.3
    - Send2Trash==1.8.3
    - sentry-sdk==2.11.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - smplx==0.1.28
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.6.2
    - supervision==0.22.0
    - termcolor==2.3.0
    - terminado==0.18.1
    - tf-keras==2.15.0
    - tfds-nightly==4.9.2.dev202308090034
    - threadpoolctl==3.5.0
    - tifffile==2024.7.24
    - timm==0.4.12
    - tinycss2==1.3.0
    - tokenizers==0.13.3
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.1
    - tqdm==4.66.0
    - traitlets==5.14.3
    - transformers==4.25.1
    - triton==2.0.0
    - types-python-dateutil==2.9.0.20240316
    - typing_extensions==4.12.2
    - uri-template==1.3.0
    - urllib3==2.2.3
    - wcwidth==0.2.13
    - webcolors==24.6.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - Werkzeug==3.0.3
    - wrapt==1.16.0
    - xtcocotools==1.14.3
    - yapf==0.40.2
    - yarl==1.9.4
    - zarr==2.18.2
    - zipp==3.19.2
    - zstandard==0.23.0
    - pandas==2.0.3
    - dill==0.3.8
    - av==12.3.0
    - yacs==0.1.8
    - klampt==0.9.1
    - jaxtyping==0.2.34
    - Pillow==10.4.0
    - pyglet==1.5.29
    - gsplat==1.4.0
    - starst3r==0.3.0
    - pyarrow==16.1.0
    - imagecodecs==2022.9.26
    - clip @ git+https://github.com/openai/CLIP.git
    # requires librealsense https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md
    - pyrealsense2==2.55.1.6486
    - ur-rtde==1.5.9
    - https://artifactory.kinovaapps.com:443/artifactory/generic-public/kortex/API/2.6.0/kortex_api-2.6.0.post3-py3-none-any.whl
    - spnav @ https://github.com/cheng-chi/spnav/archive/c1c938ebe3cc542db4685e0d13850ff1abfdb943.tar.gz
    - -e ti/devices/gello_software/third_party/DynamixelSDK/python/
    - -e ti/devices/gello_software/
    - -e third_party/robosuite/
    - -e third_party/robomimic/ 
    - setuptools==69.5.1
    - -e third_party/Grounded-Segment-Anything/segment_anything 
    - -e third_party/Grounded-Segment-Anything/recognize-anything
    - mmcv-full @ https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/mmcv_full-1.7.2-cp310-cp310-manylinux1_x86_64.whl
    - git+https://github.com/NVlabs/nvdiffrast.git
    - -e .
    - pydantic==1.10.17
    - decord==0.6.0
    - open-clip-torch==2.17.1
    - altair==5.4.0
    - pydantic==1.10.17